### ISSUE TITLE
[Upload] Design functionality for detection of duplication of the content

### ISSUE THREAD

**Issue by Ibtihel-ouni** [WomenPlusPlus/deploy-impact-22-openedu-e#8]
More work needed - design/experiment for more concrete functionality specification.

## Update October 27th

Following the[ Moderation System Flow Chart](https://miro.com/app/board/uXjVPRFpfAs=/?moveToWidget=3458764536748563901&cot=14) on Miro, the duplicates-detection functionality can be implemented as one of the "Quality check" steps executed by the moderator (not from the uploader).

- We can think about a button in the Django form received by the moderator that when clicked launches a script that compares the description similarity between the new project received and descriptions of all the other projects currently stored on the OpenEdu database. After this, the top 3 most similar projects in store are picked and flagged to the moderator as possible similar content.

- Technically speaking, we can consider using a pre-trained model from [SBERT](https://www.sbert.net/index.html#) to compare the semantic similarity of the text description of new uploaded project with that of the other projects listed in the database. These models were briefly discussed during the NLP workshop.

- These models essentially break text in sentences, produce word embeddings (i.e., vectors in a multidimensional space) of the text, calculate cosine similarity (scale -1 to 1, with 1 being identical text and -1 being opposite) and can show the top 3-5 most similar texts.

- One of the lightest and fastest pre-trained model we should consider is probably [all-MiniLM-L6-v2](https://www.sbert.net/docs/pretrained_models.html) .

**Comment by slashlan** [comment]
Just pushed on [our NLP branch](https://github.com/WomenPlusPlus/deploy-impact-22-openedu-e/tree/NLP/src/OpenEdu_upload_form) a script/Jupyter notebook test of the duplicates detection functionality for moderators. 

Ideally the Duplicates_main.py should be plugged into a Django interface for the moderator to be used. The script can be used to extract text from the new content submitted via uploading form to OpenEdu, comparing it with the instances stored in the OpenEdu database and suggesting to the moderator similar content already existing on the platform that he/she should double-check (in order to avoid duplicates and/or aggregating the new instance in an existing one).
